apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trader-app-from-trading-engine
  labels:
    {{- include "axon-trader.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: trader-app
      {{- include "axon-trader.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: trading-engine
              {{- include "axon-trader.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trader-app-from-ui
  labels:
    {{- include "axon-trader.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: trader-app
      {{- include "axon-trader.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: trader-app-ui
              {{- include "axon-trader.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trading-engine-from-trader-app
  labels:
    {{- include "axon-trader.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: trading-engine
      {{- include "axon-trader.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: trader-app
              {{- include "axon-trader.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
