apiVersion: v1
kind: Secret
metadata:
  name: axon-trader-credentials
  labels:
    {{- include "axon-trader.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.database.username | b64enc | quote }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  rabbitmq-username: {{ .Values.rabbitmq.username | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
